name: medimage

channels:
  - conda-forge
  - defaults
dependencies:
  - matplotlib==3.4.2
  - nibabel==3.2.1
  - pandas==1.2.1
  - pillow==8.3.1
  - pydicom=1.2.2
  - pywavelets==1.1.1
  - scikit-image==0.18.2
  - scipy==1.7.0
  - setuptools==49.6.0
  - sphinx_rtd_theme==0.5.2
  - tqdm==4.61.2
  - pip:
    - isort==5.10.1
    - ipykernel==6.15.1
    - ipywidgets==8.0.1
    - jupyter==1.0.0
    - numpy==1.20.0
    - numpyencoder==0.3.0
    - protobuf==3.17.3
    - ray==1.13.1
    - simpleitk==2.0.2
    - sphinx==5.1.1
    - sphinx-autodoc-typehints==1.19.2
    - sphinx-jinja2-compat==0.1.2
    - sphinx-jsonschema==1.19.1
    - sphinx-prompt==1.5.0
    - sphinx-rtd-dark-mode==1.2.4
    - wget==3.2
